Fix mkdir error in taskExtract on PHP 8
If you use `taskExtract` on PHP 8 with `error_reporting = E_ALL`, the task will always produce this error:
```
ERROR: mkdir(): File exists
in /vendor/consolidation/robo/src/Task/Archive/Extract.php:105
``` 
It happens because the line mentioned in the error message uses error suppression on `mkdir()` when trying to create a parent directory for the extraction destination folder:
```
@mkdir(dirname($this->to));
```
The parent folder will almost always exist, so an error will be emitted, and on PHP 8 the `@` operator does not work anymore for certain cases, such as the `E_ALL` level of error reporting.