Fix `Process::inheritEnvironmentVariables()` deprecation error
We're running into the following error when using `env()`:

> ERROR: The "Symfony\Component\Process\Process::inheritEnvironmentVariables()" method is deprecated since Symfony 4.4, env variables are always inherited.

The method call can be safely removed as the current required version of `symfony/process` is "^4.4.9 || ^5 || ^6".